### ISSUE TITLE
Remove hover effect

### ISSUE THREAD

**Issue by AnshuPathak-88825** [RakeshSangem/todo-app#1]
### Remove hover from from task complete button that's not looking good and little bit confused me to whether I click buttons on not
https://user-images.githubusercontent.com/78332454/179063703-cdd2bd75-b558-4c83-af80-d862ae9de1c1.mp4

**Comment by RakeshSangem** [comment]
Thank you for addressing the Issue! 

If you want to work on this I can assign this to you! request for PR we'll look into that!

**Comment by AnshuPathak-88825** [comment]
thanks for assigning me

**Comment by AnshuPathak-88825** [comment]
PR created this issue #2
